apiVersion: v1
kind: Service
metadata:
  name: securevault-frontend-service
spec:
  type: NodePort
  selector:
    app: securevault
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080

